### ISSUE TITLE
Question about dotfiles

### ISSUE THREAD

**Issue by BigLadDylan** [Cybersnake223/Hypr#1]
Hello, apologies for contacting you this way.

I love your dotfiles, (I am more of a dark-onedark kinda guy but still!)

Its not everyday that I look at dotfiles so forgive my inexperience,

Could you please let me know what you have below the waybar? is it some sort of rofi launcher? Because I want my rofi to look like that. Something similar to the noice.nvim bar
![image](https://github.com/Cybersnake223/Hypr/assets/76881322/7ece0bb5-027a-42d1-b0fa-8ef247c5022d)

Thanks again!

**Comment by Cybersnake223** [comment]
Its my terminal emulator (Foot Terminal) which i open like scratchpad for one liners.  
I Open it with 1040,50 size to make it look like this.
