### ISSUE TITLE
`powermenu` missing icons

### ISSUE THREAD

**Issue by mindrunner** [Cybersnake223/Hypr#2]
![image](https://github.com/Cybersnake223/Hypr/assets/1413542/683adef8-33a8-42e9-8213-ea469a965646)

I am probably missing a font, but unsure which one.

**Comment by Cybersnake223** [comment]
install ttf-icomoon-feather.

**Comment by mindrunner** [comment]
hmm, that did something, but not really what I expected :D

![image](https://github.com/Cybersnake223/Hypr/assets/1413542/3174d28a-a830-43a2-8e17-28108466bcaf)

**Comment by Cybersnake223** [comment]
I have added all the required icon fonts in the repo. add them to your `/usr/share/fonts/icon-fonts` and update the font cache with `fc-cache -f`

**Comment by Cybersnake223** [comment]
> I have added icon fonts in the repo itself . copy them to `/usr/share/icon-fonts` and update the font cache with `fc-cache -f `

**Comment by mindrunner** [comment]
That works. Thanks!

![image](https://github.com/Cybersnake223/Hypr/assets/1413542/4aab315b-b22f-4df8-a5a6-0ce50faef784)

Uptime icon still missing, tho

Just for reference. It's probably better to store them in 
`$HOME/.fonts/`

**Comment by Cybersnake223** [comment]
Added all the required fonts in the repo.
