### ISSUE TITLE
Waybar not working

### ISSUE THREAD

**Issue by Morbiuzx** [Cybersnake223/Hypr#5]
Installed this to try it and waybar was "working" but not showing at all, after 20 minutes trying to solve the issue I realized that the config file is set to open in a specific monitor (yours, I guess). Yay also didnt want to install anything because, again, it was configured to download to your home folder (Cybersnake). I dont even want to know what else may be specifically configured for your PC

**Comment by Cybersnake223** [comment]
Sorry my bad
Its fixed now.
